### ISSUE TITLE
gc caused segmentation violation, with generated codes by c-for-go

### ISSUE THREAD

**Issue by dtynn** [filecoin-project/filecoin-ffi#72]
### description
segmentation violation fatal when calling `packSXXXX` functions generated by `c-for-go`

### reproduce
OS:
```
➜  go-gc git:(dev) uname -r
3.10.0-957.el7.x86_64
➜  go-gc git:(dev) cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)
```

hardware
Intel E5 with 16GiB ram

go version:
```
➜  go-gc git:(dev) go version
go version go1.13.4 linux/amd64
```

rust version:
```
➜  go-gc git:(dev) cargo --version
cargo 1.42.0 (86334295e 2020-01-31)
➜  go-gc git:(dev) rustc --version
rustc 1.42.0 (b8cedc004 2020-03-09)
```

fatal log:
```
unexpected fault address 0xe4760000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe4760000 pc=0x45f2baa]

goroutine 76997 [running]:
runtime.throw(0x5c12fb2, 0x5)
  /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc0271d1698 sp=0xc0271d1668 pc=0x4031372
runtime.sigpanic()
  /usr/local/go/src/runtime/signal_unix.go:401 +0x3de fp=0xc0271d16c8 sp=0xc0271d1698 pc=0x4046f2e
github.com/filecoin-project/filecoin-ffi/generated.packSFilPublicReplicaInfo(0xc03d112000, 0xad4, 0xad4, 0xe4760000)
  /Users/janedoe/Desktop/workload/lotus/extern/filecoin-ffi/generated/cgo_helpers.go:3633 +0x5a fp=0xc0271d1740 sp=0xc0271d16c8 pc=0x45f2baa
github.com/filecoin-project/filecoin-ffi/generated.FilVerifyPost(0xc181715e8c7ede93, 0x631fc98317b96c02, 0x78d1049e8f726a8b, 0x83b242221db1d9, 0x0, 0x0, 0x0, 0x6f, 0xc03d112000, 0xad4, ...)
  /Users/janedoe/Desktop/workload/lotus/extern/filecoin-ffi/generated/generated.go:642 +0x2c3 fp=0xc0271d1830 sp=0xc0271d1740 pc=0x45f6c83
github.com/filecoin-project/filecoin-ffi.VerifyPoSt(0xc039c945c0, 0x20, 0x20, 0xc02da858c0, 0x4, 0x4, 0xc000944680, 0x4, 0x4, 0xc03d0fa000, ...)
  /Users/janedoe/Desktop/workload/lotus/extern/filecoin-ffi/proofs.go:78 +0x323 fp=0xc0271d1a48 sp=0xc0271d1830 pc=0x46003f3
github.com/filecoin-project/sector-storage/ffiwrapper.verifyPost(0x6024d20, 0xc03c331080, 0xc039c945c0, 0x20, 0x20, 0xc02da858c0, 0x4, 0x4, 0xc000944680, 0x4, ...)
  /Users/janedoe/go/pkg/mod/github.com/filecoin-project/sector-storage@v0.0.0-20200406195014-a6d093838576/ffiwrapper/verifier_cgo.go:142 +0xfc fp=0xc0271d1b18 sp=0xc0271d1a48 pc=0x463b8ac
github.com/filecoin-project/sector-storage/ffiwrapper.proofVerifier.VerifyElectionPost(...)
  /Users/janedoe/go/pkg/mod/github.com/filecoin-project/sector-storage@v0.0.0-20200406195014-a6d093838576/ffiwrapper/verifier_cgo.go:129
github.com/filecoin-project/lotus/chain.(*Syncer).VerifyElectionPoStProof(0xc00204f480, 0x6024d20, 0xc03c331080, 0xc000941500, 0xc03c3526c0, 0x31, 0xc033da24b0, 0x403011a)
  /Users/janedoe/Desktop/workload/lotus/chain/sync.go:775 +0xcac fp=0xc0271d1f10 sp=0xc0271d1b18 pc=0x490c7cc
github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6(0xc02638c780, 0x1)
  /Users/janedoe/Desktop/workload/lotus/chain/sync.go:644 +0x5b fp=0xc0271d1f70 sp=0xc0271d1f10 pc=0x49176cb
github.com/Gurpartap/async.Err.func1(0xc03c293200, 0xc03c301240, 0xc03c2fcc10)
  /Users/janedoe/go/pkg/mod/github.com/!gurpartap/async@v0.0.0-20180927173644-4f7f499dd9ee/error.go:29 +0x5b fp=0xc0271d1fc8 sp=0xc0271d1f70 pc=0x46f6afb
runtime.goexit()
  /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0271d1fd0 sp=0xc0271d1fc8 pc=0x4061651
created by github.com/Gurpartap/async.Err
  /Users/janedoe/go/pkg/mod/github.com/!gurpartap/async@v0.0.0-20180927173644-4f7f499dd9ee/error.go:27 +0x8a
```

one can easily reproduce this situation with this [demo](https://github.com/dtynn/go-gc)
use `make run` and you'll see fatals like below soon enough
```
➜  go-gc git:(dev) make run
./run.sh
    Finished release [optimized] target(s) in 0.03s
rust target dir /mnt/rust/target
2020/04/08 09:10:22 20414
unexpected fault address 0x7efd85f68010
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7efd85f68010 pc=0x49b1a7]

goroutine 1 [running]:
runtime.throw(0x4d4191, 0x5)
	/home/dtynn/go/src/runtime/panic.go:774 +0x72 fp=0xc00004ddb0 sp=0xc00004dd80 pc=0x42bd72
runtime.sigpanic()
	/home/dtynn/go/src/runtime/signal_unix.go:401 +0x3de fp=0xc00004dde0 sp=0xc00004ddb0 pc=0x43e74e
github.com/dtynn/go-gc/gen.packSGogcPublicReplicaInfo(0xc0000a8000, 0x3d0900, 0x3d0900, 0x7efd85f68010)
	/home/dtynn/proj/go-gc/gen/cgo_helpers.go:196 +0x57 fp=0xc00004de50 sp=0xc00004dde0 pc=0x49b1a7
github.com/dtynn/go-gc/gen.GogcVerifyPost(0xc0000a8000, 0x3d0900, 0x3d0900, 0x3d0900)
	/home/dtynn/proj/go-gc/gen/gen.go:19 +0x8c fp=0xc00004de90 sp=0xc00004de50 pc=0x49b33c
main.main()
	/home/dtynn/proj/go-gc/main.go:44 +0x281 fp=0xc00004df60 sp=0xc00004de90 pc=0x49b831
runtime.main()
	/home/dtynn/go/src/runtime/proc.go:203 +0x21e fp=0xc00004dfe0 sp=0xc00004df60 pc=0x42d70e
runtime.goexit()
	/home/dtynn/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00004dfe8 sp=0xc00004dfe0 pc=0x455cd1
exit status 2
make: *** [run] Error 1
```

### cause
seems to be caused by golang gc
[Curious about runtime.KeepAlive usage](https://forum.golangbridge.org/t/curious-about-runtime-keepalive-usage/3530/4)

**Comment by laser** [comment]
@dtynn - Thanks for reporting this issue. Given that this is an issue with code generated by c-for-go, I think that should report the issue to the [authors of that tool](https://github.com/xlab/c-for-go). In the meantime, I will investigate a workaround.

**Comment by laser** [comment]
Note: I have confirmed that the provided test case (`1266a7`) reproduces with OSX 10.14.6.

**Comment by Stebalien** [comment]
We've re-written the bindings and dropped c-for-go.
